# -*- coding: utf-8 -*-
"""Trabalho_2_AI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RueAw8ui5k_swoY3oYlLTu8TDr0tvIcd
"""

import pandas as pd
import tensorflow as tf

data = pd.read_csv('laptop_prices.csv')

data.isnull().sum().sum()

data

data = pd.get_dummies(data, columns = ["Company","Product","TypeName","OS","Screen","Touchscreen","IPSpanel","RetinaDisplay","CPU_company","CPU_model","PrimaryStorageType","SecondaryStorageType","GPU_company","GPU_model"])

data.head()

dados = data.drop(['Price_euros'], axis=1)
alvo = data['Price_euros']

from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler(feature_range=(-1, 1))
dados = scaler.fit_transform(dados)

from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(dados, alvo, test_size=0.25, random_state=11)

model = tf.keras.models.Sequential([
  tf.keras.layers.Dense(128, activation=tf.nn.relu),
  tf.keras.layers.Dense(64, activation=tf.nn.relu),
  tf.keras.layers.Dense(32),
  tf.keras.layers.Dense(16),
  tf.keras.layers.Dense(1)
])

model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=0.001),
             loss=tf.keras.losses.MeanSquaredError(),
             metrics=[tf.keras.metrics.R2Score()])

model.fit(x_train, y_train, epochs=200)

model.evaluate(x_test, y_test)

import matplotlib.pyplot as plt

plt.figure(figsize=(12, 6))

y_pred_train = model.predict(x_train)
y_pred_test = model.predict(x_test)

plt.subplot(1, 2, 1)
plt.scatter(y_train, y_pred_train, color='blue', label='Dados do Treinamento')
plt.scatter(y_test, y_pred_test, color='green', label='Base de Teste')
plt.plot(y_train, y_train, color='black', linewidth=2, label='Linha de Regressão')
plt.legend()

plt.tight_layout()
plt.show()